// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['AlterTable'](arg1, arg2, arg3);
}

export function CancelQuery(arg1) {
  return window['go']['app']['App']['CancelQuery'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckPendingFile() {
  return window['go']['app']['App']['CheckPendingFile']();
}

export function ClearAppLogs() {
  return window['go']['app']['App']['ClearAppLogs']();
}

export function ClearQueryHistory() {
  return window['go']['app']['App']['ClearQueryHistory']();
}

export function ConnectDB(arg1) {
  return window['go']['app']['App']['ConnectDB'](arg1);
}

export function CreateTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateTable'](arg1, arg2, arg3);
}

export function DeleteAIProviderKey(arg1) {
  return window['go']['app']['App']['DeleteAIProviderKey'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['app']['App']['DeleteCredential'](arg1);
}

export function DeleteQueryHistory(arg1) {
  return window['go']['app']['App']['DeleteQueryHistory'](arg1);
}

export function DisconnectDB(arg1) {
  return window['go']['app']['App']['DisconnectDB'](arg1);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteQueryStream(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteQueryStream'](arg1, arg2, arg3);
}

export function ExecuteTransientQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteTransientQuery'](arg1, arg2);
}

export function ExplainQuery(arg1, arg2) {
  return window['go']['app']['App']['ExplainQuery'](arg1, arg2);
}

export function ExportDatabase(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportDatabase'](arg1, arg2, arg3);
}

export function ExportTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportTable'](arg1, arg2, arg3, arg4);
}

export function ExportTableAdvanced(arg1) {
  return window['go']['app']['App']['ExportTableAdvanced'](arg1);
}

export function GetAppLogs() {
  return window['go']['app']['App']['GetAppLogs']();
}

export function GetCurrentVersion() {
  return window['go']['app']['App']['GetCurrentVersion']();
}

export function GetDatabaseInfo(arg1) {
  return window['go']['app']['App']['GetDatabaseInfo'](arg1);
}

export function GetForeignKeys(arg1, arg2) {
  return window['go']['app']['App']['GetForeignKeys'](arg1, arg2);
}

export function GetFunctions(arg1) {
  return window['go']['app']['App']['GetFunctions'](arg1);
}

export function GetLocalDataEncryptionEnabled() {
  return window['go']['app']['App']['GetLocalDataEncryptionEnabled']();
}

export function GetPrimaryKeys(arg1, arg2) {
  return window['go']['app']['App']['GetPrimaryKeys'](arg1, arg2);
}

export function GetQueryHistory(arg1) {
  return window['go']['app']['App']['GetQueryHistory'](arg1);
}

export function GetQueryHistorySummary() {
  return window['go']['app']['App']['GetQueryHistorySummary']();
}

export function GetRoutineDefinition(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetRoutineDefinition'](arg1, arg2, arg3);
}

export function GetSSHHostKeyInfo(arg1, arg2) {
  return window['go']['app']['App']['GetSSHHostKeyInfo'](arg1, arg2);
}

export function GetServerProcesses(arg1) {
  return window['go']['app']['App']['GetServerProcesses'](arg1);
}

export function GetStartupFile() {
  return window['go']['app']['App']['GetStartupFile']();
}

export function GetStoredProcedures(arg1) {
  return window['go']['app']['App']['GetStoredProcedures'](arg1);
}

export function GetTableDefinition(arg1, arg2) {
  return window['go']['app']['App']['GetTableDefinition'](arg1, arg2);
}

export function GetTableIndexes(arg1, arg2) {
  return window['go']['app']['App']['GetTableIndexes'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['app']['App']['GetTables'](arg1);
}

export function GetViews(arg1) {
  return window['go']['app']['App']['GetViews'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ImportTable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ImportTable'](arg1, arg2, arg3, arg4, arg5);
}

export function InsertRowsBatch(arg1, arg2, arg3) {
  return window['go']['app']['App']['InsertRowsBatch'](arg1, arg2, arg3);
}

export function KillServerProcess(arg1, arg2) {
  return window['go']['app']['App']['KillServerProcess'](arg1, arg2);
}

export function LoadAIProviderKey(arg1) {
  return window['go']['app']['App']['LoadAIProviderKey'](arg1);
}

export function LoadSetting(arg1) {
  return window['go']['app']['App']['LoadSetting'](arg1);
}

export function LogClientEvent(arg1, arg2) {
  return window['go']['app']['App']['LogClientEvent'](arg1, arg2);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenDownloadURL(arg1) {
  return window['go']['app']['App']['OpenDownloadURL'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['app']['App']['PerformUpdate'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['app']['App']['ReadTextFile'](arg1);
}

export function SaveAIProviderKey(arg1, arg2) {
  return window['go']['app']['App']['SaveAIProviderKey'](arg1, arg2);
}

export function SaveCredential(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveCredential'](arg1, arg2, arg3);
}

export function SaveQueryHistory(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveQueryHistory'](arg1, arg2, arg3, arg4);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['app']['App']['SaveSetting'](arg1, arg2);
}

export function SearchQueryHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SearchQueryHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectExportFile(arg1) {
  return window['go']['app']['App']['SelectExportFile'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SelectImportFile() {
  return window['go']['app']['App']['SelectImportFile']();
}

export function SelectSqliteFile() {
  return window['go']['app']['App']['SelectSqliteFile']();
}

export function SetLocalDataEncryptionEnabled(arg1) {
  return window['go']['app']['App']['SetLocalDataEncryptionEnabled'](arg1);
}

export function SetReadOnly(arg1, arg2) {
  return window['go']['app']['App']['SetReadOnly'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function ToggleFavoriteQuery(arg1, arg2) {
  return window['go']['app']['App']['ToggleFavoriteQuery'](arg1, arg2);
}

export function TrustSSHHost(arg1, arg2) {
  return window['go']['app']['App']['TrustSSHHost'](arg1, arg2);
}

export function UpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateRecord'](arg1, arg2, arg3, arg4);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['app']['App']['WriteTextFile'](arg1, arg2);
}
