// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginInstall(arg1, arg2) {
  return window['go']['main']['App']['BeginInstall'](arg1, arg2);
}

export function GetLaunchContext() {
  return window['go']['main']['App']['GetLaunchContext']();
}
