// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDB(arg1) {
  return window['go']['main']['App']['ConnectDB'](arg1);
}

export function DisconnectDB() {
  return window['go']['main']['App']['DisconnectDB']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
