// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectDB(arg1:main.DBConfig):Promise<main.ConnectResult>;

export function DisconnectDB(arg1:string):Promise<string>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function GetTables(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
