// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AlterTable(arg1:string,arg2:string,arg3:main.TableChanges):Promise<string>;

export function CancelQuery(arg1:string):Promise<string>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ConnectDB(arg1:main.DBConfig):Promise<main.ConnectResult>;

export function DisconnectDB(arg1:string):Promise<string>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<main.QueryResult>;

export function ExecuteQueryStream(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteTransientQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function ExplainQuery(arg1:string,arg2:string):Promise<string>;

export function ExportTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetForeignKeys(arg1:string,arg2:string):Promise<Array<main.ForeignKey>>;

export function GetFunctions(arg1:string):Promise<Array<string>>;

export function GetPrimaryKeys(arg1:string,arg2:string):Promise<Array<string>>;

export function GetStoredProcedures(arg1:string):Promise<Array<string>>;

export function GetTableDefinition(arg1:string,arg2:string):Promise<Array<main.ColumnDefinition>>;

export function GetTableIndexes(arg1:string,arg2:string):Promise<Array<main.IndexDefinition>>;

export function GetTables(arg1:string):Promise<Array<string>>;

export function GetViews(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ImportTable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function OpenDownloadURL(arg1:string):Promise<string>;

export function PerformUpdate(arg1:string):Promise<void>;

export function SelectExportFile(arg1:string):Promise<string>;

export function SelectImportFile():Promise<string>;

export function SelectSqliteFile():Promise<string>;

export function SetReadOnly(arg1:string,arg2:boolean):Promise<string>;

export function TestConnection(arg1:main.DBConfig):Promise<string>;

export function UpdateRecord(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<string>;
