// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AlterTable(arg1:string,arg2:string,arg3:main.TableChanges):Promise<string>;

export function CancelQuery(arg1:string):Promise<string>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckPendingFile():Promise<string>;

export function ClearAppLogs():Promise<string>;

export function ClearQueryHistory():Promise<string>;

export function ConnectDB(arg1:main.DBConfig):Promise<main.ConnectResult>;

export function CreateTable(arg1:string,arg2:string,arg3:Array<main.ColumnDefinition>):Promise<string>;

export function DeleteAIProviderKey(arg1:string):Promise<string>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteQueryHistory(arg1:number):Promise<string>;

export function DisconnectDB(arg1:string):Promise<string>;

export function DropDatabase(arg1:string,arg2:string):Promise<string>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<main.QueryResult>;

export function ExecuteQueryStream(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteTransientQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function ExplainQuery(arg1:string,arg2:string):Promise<string>;

export function ExportDatabase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetAppLogs():Promise<Array<main.LogEntry>>;

export function GetCurrentVersion():Promise<string>;

export function GetDatabaseInfo(arg1:string):Promise<main.DatabaseInfo>;

export function GetForeignKeys(arg1:string,arg2:string):Promise<Array<main.ForeignKey>>;

export function GetFunctions(arg1:string):Promise<Array<string>>;

export function GetPrimaryKeys(arg1:string,arg2:string):Promise<Array<string>>;

export function GetQueryHistory(arg1:string):Promise<Array<main.QueryHistoryEntry>>;

export function GetRoutineDefinition(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetServerProcesses(arg1:string):Promise<Array<main.ServerProcess>>;

export function GetStartupFile():Promise<string>;

export function GetStoredProcedures(arg1:string):Promise<Array<string>>;

export function GetTableDefinition(arg1:string,arg2:string):Promise<Array<main.ColumnDefinition>>;

export function GetTableIndexes(arg1:string,arg2:string):Promise<Array<main.IndexDefinition>>;

export function GetTables(arg1:string):Promise<Array<string>>;

export function GetViews(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ImportTable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function KillServerProcess(arg1:string,arg2:string):Promise<void>;

export function LoadAIProviderKey(arg1:string):Promise<string>;

export function LoadSetting(arg1:string):Promise<string>;

export function LogClientEvent(arg1:string,arg2:string):Promise<string>;

export function OpenDownloadURL(arg1:string):Promise<string>;

export function PerformUpdate(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveAIProviderKey(arg1:string,arg2:string):Promise<string>;

export function SaveCredential(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveQueryHistory(arg1:string,arg2:string):Promise<string>;

export function SaveSetting(arg1:string,arg2:string):Promise<string>;

export function SearchQueryHistory(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string,arg6:number):Promise<Array<main.QueryHistoryEntry>>;

export function SelectExportFile(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectImportFile():Promise<string>;

export function SelectSqliteFile():Promise<string>;

export function SetReadOnly(arg1:string,arg2:boolean):Promise<string>;

export function TestConnection(arg1:main.DBConfig):Promise<string>;

export function ToggleFavoriteQuery(arg1:number,arg2:boolean):Promise<string>;

export function UpdateRecord(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<string>;
