// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlterTable'](arg1, arg2, arg3);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function ClearQueryHistory() {
  return window['go']['main']['App']['ClearQueryHistory']();
}

export function ConnectDB(arg1) {
  return window['go']['main']['App']['ConnectDB'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteQueryHistory(arg1) {
  return window['go']['main']['App']['DeleteQueryHistory'](arg1);
}

export function DisconnectDB(arg1) {
  return window['go']['main']['App']['DisconnectDB'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteQueryStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQueryStream'](arg1, arg2, arg3);
}

export function ExecuteTransientQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTransientQuery'](arg1, arg2);
}

export function ExplainQuery(arg1, arg2) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2);
}

export function ExportTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportTable'](arg1, arg2, arg3, arg4);
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetForeignKeys(arg1, arg2) {
  return window['go']['main']['App']['GetForeignKeys'](arg1, arg2);
}

export function GetFunctions(arg1) {
  return window['go']['main']['App']['GetFunctions'](arg1);
}

export function GetPrimaryKeys(arg1, arg2) {
  return window['go']['main']['App']['GetPrimaryKeys'](arg1, arg2);
}

export function GetQueryHistory(arg1) {
  return window['go']['main']['App']['GetQueryHistory'](arg1);
}

export function GetRoutineDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRoutineDefinition'](arg1, arg2, arg3);
}

export function GetStoredProcedures(arg1) {
  return window['go']['main']['App']['GetStoredProcedures'](arg1);
}

export function GetTableDefinition(arg1, arg2) {
  return window['go']['main']['App']['GetTableDefinition'](arg1, arg2);
}

export function GetTableIndexes(arg1, arg2) {
  return window['go']['main']['App']['GetTableIndexes'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function GetViews(arg1) {
  return window['go']['main']['App']['GetViews'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportTable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportTable'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenDownloadURL(arg1) {
  return window['go']['main']['App']['OpenDownloadURL'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function SaveCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCredential'](arg1, arg2, arg3);
}

export function SaveQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveQueryHistory'](arg1, arg2);
}

export function SelectExportFile(arg1) {
  return window['go']['main']['App']['SelectExportFile'](arg1);
}

export function SelectImportFile() {
  return window['go']['main']['App']['SelectImportFile']();
}

export function SelectSqliteFile() {
  return window['go']['main']['App']['SelectSqliteFile']();
}

export function SetReadOnly(arg1, arg2) {
  return window['go']['main']['App']['SetReadOnly'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToggleFavoriteQuery(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavoriteQuery'](arg1, arg2);
}

export function UpdateRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRecord'](arg1, arg2, arg3, arg4);
}
